# Generated by Django 5.2.3 on 2025-06-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('format', models.CharField(choices=[('Elektron', 'Elektron'), ('Bosma', 'Bosma'), ('Qo`l yozma', 'Qo`l yozma')], default='Elektron', max_length=56)),
                ('publication_type', models.CharField(max_length=256)),
                ('journal_name', models.CharField(max_length=256)),
                ('volume', models.PositiveIntegerField()),
                ('issue', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField()),
                ('pages', models.CharField(max_length=56)),
                ('bet_soni', models.PositiveIntegerField()),
                ('mualliflar_soni', models.PositiveIntegerField()),
                ('piece', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=512)),
            ],
        ),
    ]
